---
## Workflow to periodically check if there is an available newer APM agent version, e.g.
## "v1.2.3". If so, then update to it and tag this repo with that version, e.g.
## "v1.2.3".
name: bump-opbeans-go

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 20 * * 6'

permissions:
  contents: read

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
          cache-dependency-path: '**/go.sum'

      - uses: elastic/apm-pipeline-library/.github/actions/updatecli@current
        with:
          vaultUrl: ${{ secrets.VAULT_ADDR }}
          vaultRoleId: ${{ secrets.VAULT_ROLE_ID }}
          vaultSecretId: ${{ secrets.VAULT_SECRET_ID }}
          pipeline: ./.ci/bump-opbeans-go.yml
