---
## Workflow to periodically check if there is an available newer APM agent version, e.g.
## "v1.2.3". If so, then update to it and tag this repo with that version, e.g.
## "v1.2.3".
name: bump-opbeans-go

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 20 * * 6'

permissions:
  contents: read

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
          cache-dependency-path: '**/go.sum'

      - uses: elastic/oblt-actions/updatecli/run@v1
        with:
          command: "apply --config .ci/bump-opbeans-go.yml"
        env:
          GITHUB_TOKEN: ${{ secrets.UPDATECLI_GH_TOKEN }}

      - if: failure()
        uses: elastic/oblt-actions/slack/send@v1
        with:
          bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel-id: "#apm-agent-go"
          message: ":traffic_cone: updatecli failed for `${{ github.repository }}@${{ github.ref_name }}`, @robots-ci please look what's going on <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|here>"
