---
# Creates a new GitHub release if the version in go.mod changed in the main branch and
# if the tag does not exist yet.
name: create-tag

on:
  push:
    branches:
      - main
    paths:
      - go.mod

permissions:
  contents: read

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # also fetch tags

    - uses: actions/setup-go@v5
      with:
        go-version-file: go.mod

    - run: make create-release
      env:
        GH_TOKEN: ${{ secrets.CREATE_TAG_TOKEN }}
